# fly.toml app configuration file created for fly.io
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "yt-lyrics-backend"
primary_region = "lax"
kill_signal = "SIGINT"
kill_timeout = "8s"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "60s"
    method = "get"
    path = "/health"
    protocol = "http"