# nixpacks.toml

[phases.setup]
# Install system-level dependencies required for Python packages
nixPkgs = [
  "python311",
  "ffmpeg-full", # Provides ffmpeg and ffprobe
  "lame",        # For MP3 encoding with lameenc
  "git"          # Required for some pip installs
]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  # Install PyTorch with CPU-only specifics for Railway's environment
  "pip install torch==2.4.0 --index-url https://download.pytorch.org/whl/cpu",
  # Install other Python dependencies
  "pip install -r requirements.txt"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"