# nixpacks.toml

[phases.setup]
# Use the latest available Nixpacks providers for Node.js and Python
# Also install ffmpeg, which is required by whisper and demucs.
providers = ["node", "python"]
# System packages required for our Python dependencies and yt-dlp
# git is needed to install the latest yt-dlp from the repository if needed
aptPkgs = ["ffmpeg", "git"]

[phases.install]
# Install Node.js dependencies
# Install Python dependencies from requirements.txt
# Then, force an upgrade of yt-dlp to the absolute latest version to fix signature errors.
# Finally, install PyTorch dependencies required for Demucs with CUDA support.
cmds = [
    "npm install", 
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt", 
    "pip install --upgrade yt-dlp",
    "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu"
]

[phases.build]
# Compile TypeScript code
cmds = ["npm run build"]

[start]
# The command to start the application after a successful build
# Fix: Add Python scripts directory to PATH so demucs and whisperx executables can be found
cmd = "export PATH=$(python -m site --user-base)/bin:$PATH && npm start"