# nixpacks.toml for Railway deployment
# See https://nixpacks.com/docs/configuration/file

[phases.setup]
# Use the official NixOS channel for stability
nixPkgs = ["...", "ffmpeg-full", "python3", "nodejs-20_x"]
# Explicitly add packages required by Python dependencies
aptPkgs = ["...", "libsndfile1", "libgl1-mesa-glx", "build-essential", "libcurl4-openssl-dev"]

[phases.build]
# Commands to run before building the application
cmds = ["npm install --global pnpm", "pnpm install --frozen-lockfile"]

[start]
# Command to start the application
cmd = "npm start"