providers = ["node"]

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel", "nodejs_20", "ffmpeg", "libsndfile", "yt-dlp", "gcc"]

[phases.install]
cmds = [
  "pip3 install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu/simple",
  "pip3 install --no-cache-dir demucs",
  "npm install"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"