[phases.setup]
nixPkgs = [
  "python311",                 # Explicit Python version
  "python311Packages.pip",     # pip for Python 3.11
  "nodejs_20",                 # Explicit Node.js version used by app
  "ffmpeg",                    # Audio processing library
  "yt-dlp"                     # YouTube downloader CLI
]

[phases.install]
cmds = [
  # Install Demucs and required PyTorch libs (CPU) in one go; skip pip upgrade to avoid Nix derivation bug
  "python3 -m pip install --user --no-cache-dir demucs torch torchaudio",
  "npm install"                        # Install Node.js dependencies
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"