[phases.setup]
nixPkgs = [
  "python311",                 # Explicit Python version
  "python311Packages.pip",     # pip for Python 3.11
  "python311Packages.setuptools", # Build support for manylinux wheels
  "python311Packages.wheel",   # Wheel package support
  "nodejs_20",                 # Explicit Node.js version used by app
  "ffmpeg",                    # Audio processing library
  "libsndfile",                # Required for soundfile dependency
  "yt-dlp"                     # YouTube downloader CLI
]

[phases.install]
cmds = [
  # Install CPU-only PyTorch wheel first using the official PyTorch CPU index
  "python3 -m pip install --no-cache-dir torch --extra-index-url https://download.pytorch.org/whl/cpu",
  # Then install Demucs (pulls soundfile/librosa etc.)
  "python3 -m pip install --no-cache-dir demucs",
  "npm install"                        # Install Node.js dependencies
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"