[providers]
packages = ["node"]

[phases.setup]
nixPkgs = [
  "python311",                 # Explicit Python version
  "python311Packages.pip",     # pip for Python 3.11
  "python311Packages.setuptools", # Build support for manylinux wheels
  "python311Packages.wheel",   # Wheel package support
  "nodejs_20",                 # Explicit Node.js version used by app
  "ffmpeg",                    # Audio processing library
  "libsndfile",                # Required for soundfile dependency
  "yt-dlp"                     # YouTube downloader CLI
]

[phases.install]
cmds = [
  # Install CPU-only PyTorch wheel first using pip index URL strategy
  "pip3 install --no-cache-dir --index-url https://download.pytorch.org/whl/cpu torch",
  # Then install Demucs (pulls soundfile/librosa etc.)
  "pip3 install --no-cache-dir demucs",
  # Install Node.js dependencies using npm for Railway compatibility
  "npm install"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"