# Railway Deployment Configuration for YouTube Lyrics Backend
# Optimized for 1GB memory limit with htdemucs model

[phases.setup]
nixPkgs = [
  "python311",
  "nodejs_20",
  "npm",
  "ffmpeg",
  "pkg-config",
  "libsndfile",
  "portaudio",
  "curl",
  "git"
]

[phases.install]
cmds = [
  # Install PyTorch CPU-only for memory efficiency
  "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu",
  # Install Python dependencies
  "pip install -r requirements.txt",
  # Install ALL Node.js dependencies (including devDependencies for build)
  "npm ci"
]

[phases.build]
cmds = [
  # Build TypeScript
  "npm run build",
  # Remove devDependencies after build to save space
  "npm prune --production"
]

[start]
cmd = "node dist/index.js"

[variables]
# Railway memory optimization environment variables
PYTORCH_CUDA_ALLOC_CONF = "max_split_size_mb:128"
TORCHAUDIO_BACKEND = "soundfile"
NODE_OPTIONS = "--max-old-space-size=512"
# Demucs memory optimization
DEMUCS_MEMORY_SAFE = "true"
DEMUCS_SEGMENT_LENGTH = "15"
DEMUCS_DEVICE = "cpu"