# nixpacks.toml

[phases.setup]
# Use the latest available Nixpacks providers for Node.js and Python
# Also install ffmpeg, which is required by whisper and demucs.
providers = ["node", "python"]
# System packages required for our Python dependencies and yt-dlp
# git is needed to install the latest yt-dlp from the repository if needed
# Add build-essential tools for compiling Python packages
aptPkgs = ["ffmpeg", "git", "gcc", "g++", "libsndfile1-dev", "libffi-dev", "libssl-dev", "libcurl4-openssl-dev", "wget"]

[phases.install]
# Install Node.js dependencies first
# Then install PyTorch first (large foundational dependency)
# Install other Python dependencies from requirements.txt
# Finally, upgrade yt-dlp to the absolute latest version to fix signature errors.
cmds = [
    "npm install", 
    "pip install --upgrade pip setuptools wheel",
    "pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu",
    "pip install -r requirements.txt", 
    "pip install --upgrade --force-reinstall git+https://github.com/yt-dlp/yt-dlp.git"
]

[phases.build]
# Compile TypeScript code
cmds = ["npm run build"]

[start]
# The command to start the application after a successful build
# Fix: Add Python scripts directory to PATH so demucs and whisperx executables can be found
cmd = "export PATH=$(python -m site --user-base)/bin:$PATH && npm start"